<a href="https://colab.research.google.com/github/Pedro1697/Car-Price-Prediction/blob/main/CarPrice_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [118]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

## Importing Dataset

In [119]:
df = pd.read_csv('/content/CarPrice_Assignment.csv')
df.head(10)

car_ID  symboling                   CarName fueltype aspiration doornumber  \
0       1          3        alfa-romero giulia      gas        std        two   
1       2          3       alfa-romero stelvio      gas        std        two   
2       3          1  alfa-romero Quadrifoglio      gas        std        two   
3       4          2               audi 100 ls      gas        std       four   
4       5          2                audi 100ls      gas        std       four   
5       6          2                  audi fox      gas        std        two   
6       7          1                audi 100ls      gas        std       four   
7       8          1                 audi 5000      gas        std       four   
8       9          1                 audi 4000      gas      turbo       four   
9      10          0       audi 5000s (diesel)      gas      turbo        two   

       carbody drivewheel enginelocation  wheelbase  ...  enginesize  \
0  convertible        rwd          front       88.6  ...         130   
1  convertible        rwd          front       88.6  ...         130   
2    hatchback        rwd          front       94.5  ...         152   
3        sedan        fwd          front       99.8  ...         109   
4        sedan        4wd          front       99.4  ...         136   
5        sedan        fwd          front       99.8  ...         136   
6        sedan        fwd          front      105.8  ...         136   
7        wagon        fwd          front      105.8  ...         136   
8        sedan        fwd          front      105.8  ...         131   
9    hatchback        4wd          front       99.5  ...         131   

   fuelsystem  boreratio  stroke compressionratio horsepower  peakrpm citympg  \
0        mpfi       3.47    2.68              9.0        111     5000      21   
1        mpfi       3.47    2.68              9.0        111     5000      21   
2        mpfi       2.68    3.47              9.0        154     5000      19   
3        mpfi       3.19    3.40             10.0        102     5500      24   
4        mpfi       3.19    3.40              8.0        115     5500      18   
5        mpfi       3.19    3.40              8.5        110     5500      19   
6        mpfi       3.19    3.40              8.5        110     5500      19   
7        mpfi       3.19    3.40              8.5        110     5500      19   
8        mpfi       3.13    3.40              8.3        140     5500      17   
9        mpfi       3.13    3.40              7.0        160     5500      16   

   highwaympg      price  
0          27  13495.000  
1          27  16500.000  
2          26  16500.000  
3          30  13950.000  
4          22  17450.000  
5          25  15250.000  
6          25  17710.000  
7          25  18920.000  
8          20  23875.000  
9          22  17859.167  

[10 rows x 26 columns]

In [120]:
df_without_misinformation = df

In [121]:
df_without_misinformation.isna().sum()

car_ID              0
symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

In [122]:
df_without_misinformation.duplicated().sum()

0

## Divide our indepedient variables and dependient variable

In [123]:
X = df_without_misinformation.iloc[:,1:-1]
Y = df_without_misinformation.iloc[:,-1]

In [124]:
X.head(5)

symboling                   CarName fueltype aspiration doornumber  \
0          3        alfa-romero giulia      gas        std        two   
1          3       alfa-romero stelvio      gas        std        two   
2          1  alfa-romero Quadrifoglio      gas        std        two   
3          2               audi 100 ls      gas        std       four   
4          2                audi 100ls      gas        std       four   

       carbody drivewheel enginelocation  wheelbase  carlength  ...  \
0  convertible        rwd          front       88.6      168.8  ...   
1  convertible        rwd          front       88.6      168.8  ...   
2    hatchback        rwd          front       94.5      171.2  ...   
3        sedan        fwd          front       99.8      176.6  ...   
4        sedan        4wd          front       99.4      176.6  ...   

   cylindernumber  enginesize  fuelsystem boreratio stroke  compressionratio  \
0            four         130        mpfi      3.47   2.68               9.0   
1            four         130        mpfi      3.47   2.68               9.0   
2             six         152        mpfi      2.68   3.47               9.0   
3            four         109        mpfi      3.19   3.40              10.0   
4            five         136        mpfi      3.19   3.40               8.0   

  horsepower  peakrpm  citympg  highwaympg  
0        111     5000       21          27  
1        111     5000       21          27  
2        154     5000       19          26  
3        102     5500       24          30  
4        115     5500       18          22  

[5 rows x 24 columns]

## Indentify our unique values in our categorical data

In [125]:
unique_CarName = X['CarName'].nunique()
unique_CarName

147

In [126]:
unique_fueltype = X['fueltype'].nunique()
unique_fueltype

2

In [127]:
unique_aspiration = X['aspiration'].nunique()
unique_aspiration

2

In [128]:
unique_doornumber = X['doornumber'].nunique()
unique_doornumber

2

In [129]:
unique_carbody = X['carbody'].nunique()
unique_carbody

5

In [130]:
unique_drivewheel = X['drivewheel'].nunique()
unique_drivewheel

3

In [131]:
unique_enginelocation = X['enginelocation'].nunique()
unique_enginelocation

2

In [132]:
unique_enginetype = X['enginetype'].nunique()
unique_enginetype

7

In [133]:
unique_cylindernumber = X['cylindernumber'].nunique()
unique_cylindernumber

7

In [134]:
unique_fuelsystem = X['fuelsystem'].nunique()
unique_fuelsystem

8

## Delete columns

In [135]:
X_dropped = X.drop(['CarName','enginelocation','doornumber','fueltype'],axis=1)
X_dropped

symboling aspiration      carbody drivewheel  wheelbase  carlength  \
0            3        std  convertible        rwd       88.6      168.8   
1            3        std  convertible        rwd       88.6      168.8   
2            1        std    hatchback        rwd       94.5      171.2   
3            2        std        sedan        fwd       99.8      176.6   
4            2        std        sedan        4wd       99.4      176.6   
..         ...        ...          ...        ...        ...        ...   
200         -1        std        sedan        rwd      109.1      188.8   
201         -1      turbo        sedan        rwd      109.1      188.8   
202         -1        std        sedan        rwd      109.1      188.8   
203         -1      turbo        sedan        rwd      109.1      188.8   
204         -1      turbo        sedan        rwd      109.1      188.8   

     carwidth  carheight  curbweight enginetype cylindernumber  enginesize  \
0        64.1       48.8        2548       dohc           four         130   
1        64.1       48.8        2548       dohc           four         130   
2        65.5       52.4        2823       ohcv            six         152   
3        66.2       54.3        2337        ohc           four         109   
4        66.4       54.3        2824        ohc           five         136   
..        ...        ...         ...        ...            ...         ...   
200      68.9       55.5        2952        ohc           four         141   
201      68.8       55.5        3049        ohc           four         141   
202      68.9       55.5        3012       ohcv            six         173   
203      68.9       55.5        3217        ohc            six         145   
204      68.9       55.5        3062        ohc           four         141   

    fuelsystem  boreratio  stroke  compressionratio  horsepower  peakrpm  \
0         mpfi       3.47    2.68               9.0         111     5000   
1         mpfi       3.47    2.68               9.0         111     5000   
2         mpfi       2.68    3.47               9.0         154     5000   
3         mpfi       3.19    3.40              10.0         102     5500   
4         mpfi       3.19    3.40               8.0         115     5500   
..         ...        ...     ...               ...         ...      ...   
200       mpfi       3.78    3.15               9.5         114     5400   
201       mpfi       3.78    3.15               8.7         160     5300   
202       mpfi       3.58    2.87               8.8         134     5500   
203        idi       3.01    3.40              23.0         106     4800   
204       mpfi       3.78    3.15               9.5         114     5400   

     citympg  highwaympg  
0         21          27  
1         21          27  
2         19          26  
3         24          30  
4         18          22  
..       ...         ...  
200       23          28  
201       19          25  
202       18          23  
203       26          27  
204       19          25  

[205 rows x 20 columns]

## Encoding categorical data

In [136]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [137]:
X_dropped.columns

Index(['symboling', 'aspiration', 'carbody', 'drivewheel', 'wheelbase',
       'carlength', 'carwidth', 'carheight', 'curbweight', 'enginetype',
       'cylindernumber', 'enginesize', 'fuelsystem', 'boreratio', 'stroke',
       'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg'],
      dtype='object')

In [138]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1,2,3,9,10,12])],remainder='passthrough')
X_array = np.array(ct.fit_transform(X_dropped))
print(X_array)

[[1.0e+00 0.0e+00 1.0e+00 ... 5.0e+03 2.1e+01 2.7e+01]
 [1.0e+00 0.0e+00 1.0e+00 ... 5.0e+03 2.1e+01 2.7e+01]
 [1.0e+00 0.0e+00 0.0e+00 ... 5.0e+03 1.9e+01 2.6e+01]
 ...
 [1.0e+00 0.0e+00 0.0e+00 ... 5.5e+03 1.8e+01 2.3e+01]
 [0.0e+00 1.0e+00 0.0e+00 ... 4.8e+03 2.6e+01 2.7e+01]
 [0.0e+00 1.0e+00 0.0e+00 ... 5.4e+03 1.9e+01 2.5e+01]]


## Splitting the dataset into training set and test set

In [139]:
from sklearn.model_selection import train_test_split

In [140]:
X_train, X_test,y_train,y_test = train_test_split(X_array,Y,test_size=0.2,random_state=0)

## Training the Multiple Linear Regression model on the training set

In [141]:
from sklearn.linear_model import LinearRegression

In [142]:
regressor = LinearRegression()
regressor.fit(X_train,np.array(y_train))

LinearRegression()

## Predicting the Test set results

In [143]:
y_pred = regressor.predict(X_test)

## Evaluating the model

In [144]:
from sklearn.metrics import mean_absolute_error,r2_score

In [145]:
mse = mean_absolute_error(y_test,y_pred)
r2 = r2_score(y_test,y_pred)

print(f"Mean Squared Error (MSE):{mse}")
print(f"R-Squared: {r2}")

Mean Squared Error (MSE):2321.7473957394277
R-Squared: 0.8551984113221524
